//! Present a symbol in the flavor the document is **authored** in.
//!
//! Symbols are collected from the shared `osprey_ast::Program`, which is
//! flavor-blind by [FLAVOR-BOUNDARY] — both frontends meet there and the
//! spelling that produced it is gone. So the flavor is re-applied here, at the
//! presentation edge and nowhere else: an ML author hovering `inc` reads
//! `inc : int -> int`, not the Default `fn inc(x: int) -> int` they never
//! wrote. Implements [FLAVOR-ML-FN] (curried signature line),
//! [FLAVOR-ML-GENERICS] (binder on the signature), [LSP-FLAVOR-RENDER].
//!
//! Everything here is a pure string function over the closed set of spellings
//! `analysis.rs` emits, so it is total: an input it does not recognise is
//! returned unchanged rather than mangled.

use osprey_syntax::Flavor;

/// The markdown code-fence language for `flavor`. The VSIX registers
/// `osprey-ml` as a language in its own right with its own `TextMate` grammar
/// (`source.osprey-ml`), so ML hover text fenced as `osprey` is highlighted by
/// brace-flavor rules that do not apply to it.
#[must_use]
pub const fn fence(flavor: Flavor) -> &'static str {
    match flavor {
        Flavor::Default => "osprey",
        Flavor::Ml => "osprey-ml",
    }
}

/// Re-spell one rendered Default signature for `flavor`. Default documents get
/// their input back untouched — Default *is* the canonical rendering.
#[must_use]
pub fn signature(flavor: Flavor, sig: &str) -> String {
    match flavor {
        Flavor::Default => sig.to_owned(),
        Flavor::Ml => ml_signature(sig),
    }
}

/// Re-spell a whole rendered hover block — fenced signature followed by prose —
/// for `flavor`. Built-in documentation is generated by `osprey_types` in
/// canonical Default spelling and stays flavor-blind by design: the reference is
/// **one** document, only its presentation varies.
///
/// Only the FIRST fenced block is touched, because only it is the signature. A
/// later `**Example**` block holds real Default source; re-labelling it
/// `osprey-ml` would claim it parses as ML, which it does not.
#[must_use]
pub fn hover_markdown(flavor: Flavor, md: &str) -> String {
    if flavor == Flavor::Default {
        return md.to_owned();
    }
    let mut out: Vec<String> = Vec::new();
    let mut state = 0u8; // 0 = before the block, 1 = inside it, 2 = past it.
    for line in md.lines() {
        out.push(match (state, line.starts_with("```")) {
            (0, true) => {
                state = 1;
                format!("```{}", fence(flavor))
            }
            (1, true) => {
                state = 2;
                line.to_owned()
            }
            (1, false) => signature(flavor, line),
            _ => line.to_owned(),
        });
    }
    out.join("\n")
}

/// `fn f(a: A) -> R` ⇒ `f : A -> R`; `type Box<T>` ⇒ `type Box T`;
/// `x: int` ⇒ `x : int`. Anything else passes through.
fn ml_signature(sig: &str) -> String {
    if let Some(rest) = sig.strip_prefix("fn ") {
        return ml_function(rest);
    }
    for keyword in ["type ", "effect "] {
        if let Some(rest) = sig.strip_prefix(keyword) {
            return format!("{keyword}{}", ml_binder(rest));
        }
    }
    match sig.split_once(": ") {
        // A binding's `name: type`. ML spaces the ascription (`name : type`),
        // and only the FIRST colon is the ascription — the type may hold more.
        Some((name, ty)) if !name.contains(['(', ' ']) => {
            format!("{name} : {}", ml_type(ty))
        }
        _ => sig.to_owned(),
    }
}

/// `pick<T>(a: T, b: T) -> T` ⇒ `pick<T> : T -> T -> T`. Parameter *names* have
/// no place on an ML signature line (they belong to the clause head), so only
/// the types survive, right-associated per [FLAVOR-ML-FN]. A niladic function
/// takes `Unit`, matching how the ML lowerer spells a zero-argument binding.
fn ml_function(rest: &str) -> String {
    let Some((head, params, tail)) = split_params(rest) else {
        return format!("fn {rest}");
    };
    // The head keeps its angle brackets: [FLAVOR-ML-GENERICS] binds *function*
    // type parameters on the signature line (`pick<T> : (T, T) -> T`) and only
    // *declarations* juxtapose (`type Box T`). Stripping them here would spell
    // `pick T : …`, which reads as a first parameter named `T`.
    format!(
        "{} : {}",
        head.trim(),
        arrow_chain(&params, &tail, param_type)
    )
}

/// The `A -> B -> R` spine of a parameter list and its `-> R` tail. An empty
/// list takes `Unit`, matching how the ML lowerer spells a niladic binding.
fn arrow_chain(params: &str, tail: &str, param: impl Fn(&str) -> String) -> String {
    let ret = tail.trim().strip_prefix("->").map_or("Unit", str::trim);
    let mut arrows: Vec<String> = split_top(params).iter().map(|p| param(p)).collect();
    if arrows.is_empty() {
        arrows.push(String::from("Unit"));
    }
    arrows.push(ml_type(ret));
    arrows.join(" -> ")
}

/// One parameter's type. An unannotated parameter has no ML signature spelling,
/// so it shows as the wildcard `_` rather than leaking its Default name.
fn param_type(param: &str) -> String {
    param
        .split_once(':')
        .map_or_else(|| String::from("_"), |(_, ty)| ml_type(ty.trim()))
}

/// `Box<T, out U>` ⇒ `Box T out U` — ML binds type parameters by juxtaposition
/// on declarations. A binder-free name passes through. [FLAVOR-ML-GENERICS]
fn ml_binder(decl: &str) -> String {
    let Some((name, args)) = decl.split_once('<') else {
        return decl.to_owned();
    };
    let Some(args) = args.strip_suffix('>') else {
        return decl.to_owned();
    };
    format!("{name} {}", split_top(args).join(" "))
}

/// A written type in ML spelling: a function type loses its `fn` keyword and
/// becomes parenthesised arrows (`fn(int) -> int` ⇒ `(int -> int)`), which is
/// how it must read nested inside a larger signature. [FLAVOR-ML-FN]
fn ml_type(ty: &str) -> String {
    let ty = ty.trim();
    let Some(rest) = ty.strip_prefix("fn") else {
        return ty.to_owned();
    };
    let Some((head, params, tail)) = split_params(rest) else {
        return ty.to_owned();
    };
    if !head.trim().is_empty() {
        return ty.to_owned();
    }
    format!("({})", arrow_chain(&params, &tail, ml_type))
}

/// Split `head(inner)tail` at the parameter list's **balanced** parentheses, so
/// a function-typed parameter (`f: fn(int) -> int`) does not end the list early.
/// Owned pieces: the caller re-spells them, and borrowing would pin every
/// caller to a temporary it does not want to name.
fn split_params(rest: &str) -> Option<(String, String, String)> {
    let open = rest.find('(')?;
    let mut depth = 0usize;
    let close = rest[open..].char_indices().find_map(|(offset, c)| {
        match c {
            '(' => depth += 1,
            ')' => depth -= 1,
            _ => (),
        }
        (depth == 0).then_some(open + offset)
    })?;
    Some((
        rest[..open].to_owned(),
        rest[open + 1..close].to_owned(),
        rest[close + 1..].to_owned(),
    ))
}

/// Comma-split at nesting depth zero, dropping blanks — `int, fn(a, b) -> c`
/// is two items, not four.
fn split_top(list: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut depth = 0usize;
    let mut start = 0usize;
    for (i, c) in list.char_indices() {
        match c {
            '(' | '<' => depth += 1,
            ')' | '>' => depth = depth.saturating_sub(1),
            ',' if depth == 0 => {
                out.push(list[start..i].trim().to_owned());
                start = i + 1;
            }
            _ => (),
        }
    }
    out.push(list[start..].trim().to_owned());
    out.retain(|item| !item.is_empty());
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ml_documents_get_the_ml_fence_and_default_documents_do_not() {
        assert_eq!(fence(Flavor::Ml), "osprey-ml");
        assert_eq!(fence(Flavor::Default), "osprey");
    }

    #[test]
    fn a_default_signature_is_respelled_as_an_ml_signature_line() {
        // [FLAVOR-ML-FN]: parameter names live on the clause head, types on the
        // signature line, right-associated. A niladic function takes `Unit`.
        assert_eq!(
            signature(Flavor::Ml, "fn inc(x: int) -> int"),
            "inc : int -> int"
        );
        assert_eq!(
            signature(Flavor::Ml, "fn add(a: int, b: int) -> int"),
            "add : int -> int -> int"
        );
        assert_eq!(
            signature(Flavor::Ml, "fn now() -> int"),
            "now : Unit -> int"
        );
        // [FLAVOR-ML-GENERICS]: the binder stays angle-bracketed on a function
        // signature but juxtaposes on a declaration.
        assert_eq!(
            signature(Flavor::Ml, "fn pick<T>(a: T, b: T) -> T"),
            "pick<T> : T -> T -> T"
        );
        assert_eq!(signature(Flavor::Ml, "type Box<T>"), "type Box T");
        assert_eq!(
            signature(Flavor::Ml, "effect Feed<out T>"),
            "effect Feed out T"
        );
        // A binding ascription gains ML's spaced colon.
        assert_eq!(signature(Flavor::Ml, "total: int"), "total : int");
        // Default documents are never rewritten.
        assert_eq!(
            signature(Flavor::Default, "fn inc(x: int) -> int"),
            "fn inc(x: int) -> int"
        );
    }

    #[test]
    fn a_function_typed_parameter_keeps_its_arrows_balanced() {
        // The naive `find(')')` split ends the list inside `fn(int) -> int` and
        // produces `map : (int -> int` — unbalanced, and wrong about the arity.
        assert_eq!(
            signature(Flavor::Ml, "fn map(f: fn(int) -> int, x: int) -> int"),
            "map : (int -> int) -> int -> int"
        );
        assert_eq!(
            signature(Flavor::Ml, "fn mk() -> fn(int, int) -> int"),
            "mk : Unit -> (int -> int -> int)"
        );
    }

    #[test]
    fn an_unannotated_parameter_shows_as_a_wildcard_not_its_name() {
        // Its Default rendering is the bare name; echoing that into an arrow
        // chain would read as a TYPE called `x`.
        assert_eq!(signature(Flavor::Ml, "fn id(x) -> int"), "id : _ -> int");
    }

    #[test]
    fn a_builtin_doc_block_is_refenced_but_its_example_is_left_alone() {
        // Built-in docs are generated once, flavor-blind, in Default spelling.
        // The SIGNATURE block is respelled and refenced; the `**Example**`
        // block holds real Default source, so relabelling it `osprey-ml` would
        // claim it parses as ML — it does not.
        let md = "```osprey\nfn puts(s: string) -> int\n```\n\nWrites a line.\n\n\
                  **Example**\n```osprey\nputs(\"hi\")\n```";
        let ml = hover_markdown(Flavor::Ml, md);
        assert!(
            ml.starts_with("```osprey-ml\nputs : string -> int\n```"),
            "{ml}"
        );
        assert!(
            ml.contains("**Example**\n```osprey\nputs(\"hi\")\n```"),
            "{ml}"
        );
        assert_eq!(ml.matches("```").count(), 4, "fences stay balanced:\n{ml}");
        // Default documents are handed back byte-for-byte.
        assert_eq!(hover_markdown(Flavor::Default, md), md);
        // Prose with no code block at all survives unchanged.
        assert_eq!(hover_markdown(Flavor::Ml, "just prose"), "just prose");
    }

    #[test]
    fn unrecognised_spellings_pass_through_untouched() {
        // Totality: the renderer never mangles what it cannot parse.
        for input in ["namespace app", "module Tax", "signature TaxApi", "fn ("] {
            assert_eq!(signature(Flavor::Ml, input), input);
        }
    }
}
