//! C and C++ declarations for the checked iOS library boundary. [IOS-HOST-ABI]

use super::{c_identifier, CType, HostAbi, ENTRY};
use std::fmt::Write as _;

pub(super) fn reserved_identifier(name: &str) -> bool {
    if let Some(ty) = name.strip_suffix("_t") {
        return integer_type(ty) || matches!(ty, "intptr" | "uintptr" | "intmax" | "uintmax");
    }
    if let Some((base, suffix)) = name.rsplit_once('_') {
        if matches!(suffix, "MIN" | "MAX" | "WIDTH" | "C") {
            return integer_type(&base.to_ascii_lowercase())
                || matches!(
                    base,
                    "INTPTR"
                        | "UINTPTR"
                        | "INTMAX"
                        | "UINTMAX"
                        | "PTRDIFF"
                        | "SIZE"
                        | "SIG_ATOMIC"
                        | "WCHAR"
                        | "WINT"
                );
        }
    }
    matches!(
        name,
        "__bool_true_false_are_defined" | "__cplusplus" | "__STDC__"
    )
}

fn integer_type(name: &str) -> bool {
    [
        "int",
        "uint",
        "int_least",
        "uint_least",
        "int_fast",
        "uint_fast",
    ]
    .iter()
    .any(|prefix| {
        name.strip_prefix(prefix)
            .is_some_and(|bits| matches!(bits, "8" | "16" | "32" | "64"))
    })
}

/// Render the C header a host compiles against. [IOS-HOST-ABI]
pub(crate) fn header(abi: &HostAbi, source: &str) -> String {
    header_for_target(abi, source, "ios")
}

pub(crate) fn header_for_target(abi: &HostAbi, source: &str, target: &str) -> String {
    let source = source.replace(['\n', '\r'], " ");
    let mut h = format!(
        "// Osprey {target} host ABI for {source}.\n\
         // Generated by `osprey --target={target}`; do not edit. [IOS-HOST-ABI]\n\
         #pragma once\n#include <stdbool.h>\n#include <stdint.h>\n\n\
         #ifdef __cplusplus\nextern \"C\" {{\n#endif\n\n\
         // Runs the program's top-level statements and `fn main`, returning its\n\
         // exit status. Call before any other export. Repeated calls return the\n\
         // cached status; reentrant initialization returns 1. Call all exports\n\
         // from one host thread. [IOS-TARGET-ENTRY]\n\
         int32_t {ENTRY}(void);\n"
    );
    if !abi.exports.is_empty() {
        h.push_str(
            "\n// Exports: Osprey functions the host may call. A returned string belongs\n\
             // to the Osprey runtime; copy it before the next call into the library.\n",
        );
    }
    for e in &abi.exports {
        let _ = writeln!(
            h,
            "// fn {}{}",
            e.source_name,
            osprey_signature(&e.params, e.ret)
        );
        let _ = writeln!(h, "{}", prototype(&e.c_name, &e.params, e.ret));
    }
    if !abi.imports.is_empty() {
        h.push_str(
            "\n// Imports: functions the host must define with C linkage\n\
             // (Swift: `@_cdecl(\"name\")`). Osprey calls them through `extern fn`.\n",
        );
    }
    for i in &abi.imports {
        let _ = writeln!(
            h,
            "// extern fn {}{}",
            i.symbol,
            osprey_signature(&i.params, i.ret)
        );
        let _ = writeln!(h, "{}", prototype(&i.symbol, &i.params, i.ret));
    }
    h.push_str("\n#ifdef __cplusplus\n}\n#endif\n");
    h
}

fn osprey_signature(params: &[(String, CType)], ret: CType) -> String {
    let params = params
        .iter()
        .map(|(name, c)| format!("{name}: {}", c.osprey()))
        .collect::<Vec<_>>()
        .join(", ");
    format!("({params}) -> {}", ret.osprey())
}

fn prototype(name: &str, params: &[(String, CType)], ret: CType) -> String {
    let safe_names = params.iter().all(|(n, _)| c_identifier(n));
    let params = if params.is_empty() {
        "void".to_string()
    } else {
        params
            .iter()
            .enumerate()
            .map(|(i, (n, c))| {
                c_declaration(
                    c.c(),
                    &if safe_names {
                        n.clone()
                    } else {
                        format!("osprey_arg{i}")
                    },
                )
            })
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("{}({params});", c_declaration(ret.c(), name))
}

fn c_declaration(ty: &str, name: &str) -> String {
    format!("{ty}{}{name}", if ty.ends_with('*') { "" } else { " " })
}
