import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDirectory, "..");
const SENTINEL = "__OSPREY_WASM_BASE64__";

function ospreyString(source) {
  return source
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\r", "\\r")
    .replaceAll("\n", "\\n")
    .replaceAll("\t", "\\t");
}

function argumentValue(name, fallback) {
  const index = process.argv.indexOf(name);
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1] : fallback;
}

function embedPaths(options) {
  return {
    javascriptPath: options.javascriptPath ?? path.join(packageRoot, "dist/host.js"),
    cssPath: options.cssPath ?? path.join(packageRoot, "dist/host.css"),
    wasmPath: options.wasmPath ?? path.join(packageRoot, "build/talon-client.wasm"),
    outputPath: options.outputPath ?? path.resolve(packageRoot, "../src/web/bundle.ospml"),
  };
}

async function readAssets(paths) {
  return Promise.all([
    readFile(paths.javascriptPath, "utf8"),
    readFile(paths.cssPath, "utf8"),
    readFile(paths.wasmPath),
  ]);
}

function validateAssets(javascriptSource, cssSource) {
  const occurrences = javascriptSource.split(SENTINEL).length - 1;
  if (occurrences !== 1) {
    throw new Error(`Expected one wasm embed sentinel in host.js; found ${occurrences}`);
  }
  if (javascriptSource.includes("${") || cssSource.includes("${")) {
    throw new Error("Generated assets must not contain Osprey interpolation syntax");
  }
}

function moduleSource(css, javascript) {
  return `// Generated by examples/projects/modules/web/scripts/embed.mjs. Do not edit.\n` +
    `// React is the renderer; Osprey wasm owns model/update/view and emits one JSON tree per render.\n` +
    `namespace "bank/web"\n\n` +
    `module Bundle\n` +
    `    export style : Unit -> string\n` +
    `    style () = "${ospreyString(css)}"\n\n` +
    `    export script : Unit -> string\n` +
    `    script () = "${ospreyString(javascript)}"\n`;
}

function assetStats(paths, javascript, css, wasm) {
  return {
    outputPath: paths.outputPath,
    javascriptBytes: Buffer.byteLength(javascript),
    cssBytes: Buffer.byteLength(css),
    wasmBytes: wasm.byteLength,
  };
}

export async function embed(options = {}) {
  const paths = embedPaths(options);
  const [javascriptSource, css, wasm] = await readAssets(paths);
  validateAssets(javascriptSource, css);
  const javascript = javascriptSource.replace(SENTINEL, wasm.toString("base64"));
  await mkdir(path.dirname(paths.outputPath), { recursive: true });
  await writeFile(paths.outputPath, moduleSource(css, javascript), "utf8");
  return assetStats(paths, javascript, css, wasm);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = await embed({
    javascriptPath: path.resolve(argumentValue("--javascript", path.join(packageRoot, "dist/host.js"))),
    cssPath: path.resolve(argumentValue("--css", path.join(packageRoot, "dist/host.css"))),
    wasmPath: path.resolve(argumentValue("--wasm", path.join(packageRoot, "build/talon-client.wasm"))),
    outputPath: path.resolve(argumentValue("--output", path.resolve(packageRoot, "../src/web/bundle.ospml"))),
  });
  console.log(
    `embedded ${result.wasmBytes} B wasm + ${result.javascriptBytes} B JS + ` +
      `${result.cssBytes} B CSS -> ${result.outputPath}`,
  );
}
